#
# production settings
# 
# (version: 208, saved: 2020-05-02 21:39:51)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 4670
    strings-idstart: 13
    version: 208
