#
# production settings
# 
# (version: 174, saved: 2020-04-11 23:06:32)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 9999
    strings-idstart: 13
    version: 174
