#
# production settings
# 
# (version: 1044, saved: 2020-11-12 15:48:30)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 4670
    strings-idstart: 13
    version: 1044
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\globals\\resources\\gameplay.xml"
      - ".type": CR4DefinitionsDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities\\"
      - ".type": CR4DefinitionsNGPlusDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities_plus\\"
      - ".type": CR4ScaleformContentDLCMounter
        scaleformDirectoryPath: "dlc\\dlcntr\\data\\gameplay\\gui_new\\"
