#
# production settings
# 
# (version: 1359, saved: 2021-04-18 01:17:17)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 4670
    strings-idstart: 13
    version: 1359
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\globals\\resources\\gameplay.xml"
      - ".type": CR4DefinitionsDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities\\"
      - ".type": CR4DefinitionsNGPlusDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities_plus\\"
      - ".type": CR4ScaleformContentDLCMounter
        scaleformDirectoryPath: "dlc\\dlcntr\\data\\gameplay\\gui_new\\"
