#
# production settings
# 
# (version: 757, saved: 2020-08-19 22:13:02)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 4670
    strings-idstart: 13
    version: 757
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\globals\\resources\\gameplay.xml"
