#
# production settings
# 
# (version: 783, saved: 2020-08-20 20:13:01)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 4670
    strings-idstart: 13
    version: 783
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\globals\\resources\\gameplay.xml"
      - ".type": CR4DefinitionsDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities\\"
      - ".type": CR4DefinitionsNGPlusDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\abilities_plus\\"
