#
# production settings
# 
# (version: 510, saved: 2020-07-14 23:15:54)
#
---
production:
  settings:
    id: ntr
    caption: A Night to Remember
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 4670
    strings-idstart: 13
    version: 510
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\globals\\resources\\gameplay.xml"
      - ".type": CR4DefinitionsDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\items\\ntr_def_items.xml"
      - ".type": CR4DefinitionsNGPlusDLCMounter
        definitionXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\items_plus\\ntr_def_items.xml"
      - ".type": CR4RewardsDLCMounter
        rewordsXmlFilePath: "dlc\\dlcntr\\data\\gameplay\\rewards\\ntr_rewards.xml"
